name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4

    - name: Install dependencies
      run: composer install --no-progress --no-suggest --prefer-dist

    - name: Run tests
      run: vendor/bin/phpunit --configuration phpunit.xml

  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run security scan
      uses: github/codeql-action/init@v1
      with:
        languages: php
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
      with:
        category: '/language:php'

  deploy:
    runs-on: ubuntu-latest
    needs: [build, security]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      run: ./deploy.sh
