name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_REGISTRY: localhost:5000
  APP_NAME: myapp
  Sonar_Url: https://localhost
  Sonar_Token: sonarqube
  security_scan_tool: trivy
  GIT_SHA: ${{ github.sha }}

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  install-dependencies:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Install PHP and Composer
        run: |
          sudo apt-get update
          sudo apt-get install -y php-cli unzip curl
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
      - name: Install Dependencies
        run: composer install

  build:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Build Application
        run: echo "Build step for PHP application"


  docker-build-push:
    runs-on: ubuntu-latest
    needs: quality-gate
    steps:
      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKER_REGISTRY/$APP_NAME:$GIT_SHA .
          docker push $DOCKER_REGISTRY/$APP_NAME:$GIT_SHA


